# Generated by Django 2.2.2 on 2019-06-11 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('released', models.DateField(verbose_name='release date')),
                ('rated', models.CharField(blank=True, choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=5, null=True, verbose_name='PG rating')),
                ('runtime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='runtime')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='genre')),
                ('director', models.CharField(blank=True, max_length=80, verbose_name='director')),
                ('writer', models.CharField(blank=True, max_length=255, verbose_name='writer')),
                ('actors', models.CharField(blank=True, max_length=255, verbose_name='actors')),
                ('plot', models.CharField(blank=True, max_length=255, verbose_name='plot')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='language')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('awards', models.CharField(blank=True, max_length=100, verbose_name='awards')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='rating')),
                ('box_office', models.PositiveIntegerField(blank=True, null=True, verbose_name='box office')),
                ('production', models.CharField(blank=True, max_length=100, verbose_name='production')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='movie.Movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
